/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectacai;


import javax.swing.JOptionPane;
import projectacai.ControlaVendas;
import projectacai.FrameVendas;
import projectacai.Vendas;

/**
 *
 * @author igorc
 */
public class MenuAS extends javax.swing.JFrame {
    ControlaVendas cv = new ControlaVendas();
    
    int contadorB;
    int contadorP;
    int contadorK;
    int contadorLC;
    int contadorLN;
    
   

        
   
    public MenuAS() {
        initComponents();
        setLocationRelativeTo(null);
        
    }
    
   
        
        // Defina outras propriedades e componentes conforme necessário
        // ...
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SubB = new javax.swing.JButton();
        SubP = new javax.swing.JButton();
        SubK = new javax.swing.JButton();
        SubLC = new javax.swing.JButton();
        SubLN = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        SomaK = new javax.swing.JButton();
        SomaB = new javax.swing.JButton();
        SomaP = new javax.swing.JButton();
        SomaLN = new javax.swing.JButton();
        SomaLC = new javax.swing.JButton();
        UniB = new javax.swing.JTextField();
        UniK = new javax.swing.JTextField();
        UniP = new javax.swing.JTextField();
        UniLC = new javax.swing.JTextField();
        UniLN = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        SomaK1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SubB.setText("-");
        SubB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubBActionPerformed(evt);
            }
        });

        SubP.setText("-");
        SubP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubPActionPerformed(evt);
            }
        });

        SubK.setText("-");
        SubK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubKActionPerformed(evt);
            }
        });

        SubLC.setText("-");
        SubLC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubLCActionPerformed(evt);
            }
        });

        SubLN.setText("-");
        SubLN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubLNActionPerformed(evt);
            }
        });

        jLabel1.setText("KIWI");

        jLabel2.setText("BANANA");

        jLabel3.setText("LEITE CONDENSADO");

        jLabel4.setText("PAÇOCA");

        jLabel5.setText("LEITE NINHO");

        SomaK.setText("+");
        SomaK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SomaKActionPerformed(evt);
            }
        });

        SomaB.setText("+");
        SomaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SomaBActionPerformed(evt);
            }
        });

        SomaP.setText("+");
        SomaP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SomaPActionPerformed(evt);
            }
        });

        SomaLN.setText("+");
        SomaLN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SomaLNActionPerformed(evt);
            }
        });

        SomaLC.setText("+");
        SomaLC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SomaLCActionPerformed(evt);
            }
        });

        UniB.setEditable(false);
        UniB.setText("0");
        UniB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UniBActionPerformed(evt);
            }
        });

        UniK.setEditable(false);
        UniK.setText("0");
        UniK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UniKActionPerformed(evt);
            }
        });

        UniP.setEditable(false);
        UniP.setText("0");
        UniP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UniPActionPerformed(evt);
            }
        });

        UniLC.setEditable(false);
        UniLC.setText("0");
        UniLC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UniLCActionPerformed(evt);
            }
        });

        UniLN.setEditable(false);
        UniLN.setText("0");
        UniLN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UniLNActionPerformed(evt);
            }
        });

        jLabel6.setText("MAIS DE 3 ACOMPANHAMENTOS, ACRÉSCIMO DE R$1,50 POR SABOR");

        jLabel7.setText("AÇAÍ R$15,00 REAIS COM 3 ACOMPANHAMENTOS GRATUITOS");

        jLabel8.setText("ACOMPANHAMENTOS");

        total.setEditable(false);
        total.setText("R$18.00");
        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });

        jLabel9.setText("TOTAL A PAGAR :");

        jLabel10.setText("OBS: AÇAÍ PURO  :  RS$18 REAIS");

        SomaK1.setText("FINALIZAR COMPRA");
        SomaK1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SomaK1ActionPerformed(evt);
            }
        });

        jButton1.setText("VENDAS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SubLC)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(SomaLC)
                                .addGap(18, 18, 18)
                                .addComponent(UniLC, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SubLN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(SomaLN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(UniLN, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(29, 29, 29))
                                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SubB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SomaB)
                                .addGap(18, 18, 18)
                                .addComponent(UniB, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SubP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SubK)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SomaK)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(UniK, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(SomaP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(UniP, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(121, 121, 121)
                        .addComponent(SomaK1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)))))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(total, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(SubB)
                        .addComponent(jLabel2)
                        .addComponent(SomaB)
                        .addComponent(UniB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SubK)
                    .addComponent(jLabel1)
                    .addComponent(SomaK)
                    .addComponent(UniK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SubP)
                            .addComponent(jLabel4)
                            .addComponent(SomaP)
                            .addComponent(UniP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SomaK1))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(SomaLC)
                            .addComponent(SubLC)
                            .addComponent(UniLC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SubLN)
                            .addComponent(jLabel5)
                            .addComponent(SomaLN, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UniLN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(26, 26, 26)))
                .addComponent(jLabel10)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubKActionPerformed
      if (contadorK > 0 ) {
            contadorK--;
             String numeroK = String.valueOf(contadorK);
              UniK.setText(numeroK);
        }else if(contadorK < 0){
            int zero = 0;
            String numeroK1 = String.valueOf(zero);
            UniK.setText(numeroK1);
           }else{
          contadorK = 0; 
        }
     
       if (somaDosContadores() == 0) {
            total.setText("R$18.00");
       } else if(somaDosContadores() > 0 && somaDosContadores() < 4){
           total.setText("R$15.00");
       } else{
          ajustarPreco();
       } 
                 
    }//GEN-LAST:event_SubKActionPerformed

    private void SomaLNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SomaLNActionPerformed
            contadorLN++;
    String numeroLN = String.valueOf(contadorLN);
    UniLN.setText(numeroLN);
    
 
        if (somaDosContadores()  == 0) {
            total.setText("R$18.00");
       } else if(somaDosContadores() > 0 && somaDosContadores() < 4){
           total.setText("R$15.00");
       } else{
           ajustarPreco();
       }

    }//GEN-LAST:event_SomaLNActionPerformed

    private void UniBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UniBActionPerformed
        UniB.setText("0'");
    }//GEN-LAST:event_UniBActionPerformed

    private void UniKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UniKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UniKActionPerformed

    private void UniPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UniPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UniPActionPerformed

    private void UniLCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UniLCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UniLCActionPerformed

    private void UniLNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UniLNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UniLNActionPerformed

    private void SubBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubBActionPerformed
      
   
        if (contadorB  > 0 ) {
            contadorB--;
             String numeroB = String.valueOf(contadorB);
              UniB.setText(numeroB);
        }else if(contadorB < 0){
            int zero = 0;
            String numeroB1 = String.valueOf(zero);
            UniB.setText(numeroB1);
           }else{
         contadorB = 0;    
        }
        
       
       if (somaDosContadores() == 0) {
            total.setText("R$18.0");
       } else if(somaDosContadores() > 0 && somaDosContadores() < 4){
           total.setText("R$15.0");
       } else{
         ajustarPreco();
       } 


// TODO add your handling code here:
    }//GEN-LAST:event_SubBActionPerformed

    private void SubPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubPActionPerformed
      if (contadorP > 0 ) {
            contadorP--;
             String numeroP = String.valueOf(contadorP);
              UniP.setText(numeroP);
        }else if(contadorP < 0){
            int zero = 0;
            String numeroP1 = String.valueOf(zero);
            UniP.setText(numeroP1);
           }else{}
       
       if (somaDosContadores() == 0) {
            total.setText("R$18.00");
       } else if(somaDosContadores() > 0 && somaDosContadores() < 4){
           total.setText("R$15.00");
       } else{
            ajustarPreco();
       } 

      
    }//GEN-LAST:event_SubPActionPerformed

    private void SubLCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubLCActionPerformed
       if (contadorLC > 0 ) {
            contadorLC--;
             String numeroLC = String.valueOf(contadorLC);
              UniLC.setText(numeroLC);
        }else if(contadorLC < 0){
            int zero = 0;
            String numeroLC = String.valueOf(zero);
            UniP.setText(numeroLC);
           }else{}
        
       if (somaDosContadores() == 0) {
            total.setText("R$18.00");
       } else if(somaDosContadores() > 0 && somaDosContadores() < 4){
           total.setText("R$15.00");
       } else{
          ajustarPreco();
       } 

    }//GEN-LAST:event_SubLCActionPerformed

    private void SubLNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubLNActionPerformed
        if (contadorLN > 0 ) {
            contadorLN--;
             String numeroLN = String.valueOf(contadorLN);
              UniLN.setText(numeroLN);
        }else if(contadorLN < 0){
            int zero = 0;
            String numeroLN1 = String.valueOf(zero);
            UniLN.setText(numeroLN1);
           }else{
         contadorLN = 0;    
       
       if (somaDosContadores() == 0) {
            total.setText("R$18.00");
       } else if(somaDosContadores() > 0 && somaDosContadores() < 4){
           total.setText("R$15.00");
       } else{
           ajustarPreco();
       } }

    }//GEN-LAST:event_SubLNActionPerformed

    private void SomaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SomaBActionPerformed
          contadorB++;
    String numeroB = String.valueOf(contadorB);
    UniB.setText(numeroB);
    
    ajustarPreco();        
    }//GEN-LAST:event_SomaBActionPerformed

    private void SomaKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SomaKActionPerformed
         contadorK++;
    String numeroK = String.valueOf(contadorK);
    UniK.setText(numeroK);
    
 
        if (somaDosContadores()  == 0) {
            total.setText("R$18.00");
       } else if(somaDosContadores() > 0 && somaDosContadores() < 4){
           total.setText("R$15.00");
       } else{
          ajustarPreco();
       }

    }//GEN-LAST:event_SomaKActionPerformed

    private void SomaPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SomaPActionPerformed
          contadorP++;
    String numeroP = String.valueOf(contadorP);
    UniP.setText(numeroP); 
       
       if (somaDosContadores()  == 0) {
            total.setText("R$18.00");
       } else if(somaDosContadores() > 0 && somaDosContadores() < 4){
           total.setText("R$15.00");
       } else{
          ajustarPreco();
       }

// TODO add your handling code here:
    }//GEN-LAST:event_SomaPActionPerformed

    private void SomaLCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SomaLCActionPerformed
           contadorLC++;
    String numeroLC = String.valueOf(contadorLC);
    UniLC.setText(numeroLC);
   

        if (somaDosContadores()  == 0) {
            total.setText("R$18.00");
       } else if(somaDosContadores() > 0 && somaDosContadores() < 4){
           total.setText("R$15.00");
       } else{
          ajustarPreco();
       }

    }//GEN-LAST:event_SomaLCActionPerformed

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
    total.setText("R$18.00");
    }//GEN-LAST:event_totalActionPerformed

    private void SomaK1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SomaK1ActionPerformed
   int resposta = JOptionPane.
              showConfirmDialog
        (null, "O valor total foi de : " + total.getText() + " reais, deseja prosseguir?", "Confirmação", JOptionPane.
                YES_NO_OPTION);

if (resposta == JOptionPane.YES_OPTION) {
      JOptionPane.
               showMessageDialog(null, "venda efetuada!");
      
     Vendas vendas = new Vendas();
     vendas.setvenda(total.getText());
  
      
      if(cv.salvar(vendas)) {
     total.setText("R$18.00");
     UniB.setText("0");
     UniK.setText("0");
     UniP.setText("0");
     UniLC.setText("0");
     UniLN.setText("0");
     total.requestFocus();
     UniB.requestFocus();
     UniK.requestFocus();
     UniP.requestFocus();
     UniLC.requestFocus();
     UniLN.requestFocus();
     
     contadorB = 0;
     contadorK = 0;
     contadorLC = 0;
     contadorLN = 0;
     contadorP = 0;
     
       }else {
        JOptionPane.showMessageDialog(null,"venda Cancelada!");
     
      }
    // código para continuar
} else if (resposta == JOptionPane.NO_OPTION) {
      
        JOptionPane.
               showMessageDialog(null, "venda cancelada!"); 
}

        
        
      
    }//GEN-LAST:event_SomaK1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         FrameVendas dlg = new FrameVendas(null, true, cv);
         dlg.setLocationRelativeTo(null);
         dlg.setVisible(true);
         this.dispose();       
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SomaB;
    private javax.swing.JButton SomaK;
    private javax.swing.JButton SomaK1;
    private javax.swing.JButton SomaLC;
    private javax.swing.JButton SomaLN;
    private javax.swing.JButton SomaP;
    private javax.swing.JButton SubB;
    private javax.swing.JButton SubK;
    private javax.swing.JButton SubLC;
    private javax.swing.JButton SubLN;
    private javax.swing.JButton SubP;
    private javax.swing.JTextField UniB;
    private javax.swing.JTextField UniK;
    private javax.swing.JTextField UniLC;
    private javax.swing.JTextField UniLN;
    private javax.swing.JTextField UniP;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables

    private void ajustarPreco() {
      int somaDosContadores = contadorB + contadorK  + contadorLC + contadorLN + contadorP;

        if (somaDosContadores  == 0) {
            total.setText("R$18.0");
       } else if(somaDosContadores > 0 && somaDosContadores < 4){
           total.setText("R$15.0");
       } else {
          double i = 15.00;
           double a = 1.50;
         int somaPri = somaDosContadores - 3;
        double somaPriA = somaPri;
       double somarFinal = a * somaPriA;
       double SomarTudo = i + somarFinal;
         
         total.setText("R$" + String.valueOf(SomarTudo));

}}

    private int somaDosContadores() {
       return contadorB + contadorK  + contadorLC + contadorLN + contadorP;
}}